#!/usr/bin/env python3
"""Turn part 1's assembled binary into a C header for the Pico firmware.

The emitted header carries the bytes and the address they load at, so the
firmware never has to repeat the origin from the assembly source.
"""

import argparse
import sys


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("input", help="raw binary")
    ap.add_argument("output", help="header to write")
    ap.add_argument("--name", default="rom_image", help="C identifier")
    ap.add_argument("--addr", default="0", help="load address, e.g. 0xC000")
    args = ap.parse_args()

    addr = int(args.addr, 0)
    with open(args.input, "rb") as f:
        data = f.read()

    if not data:
        print(f"{args.input}: empty", file=sys.stderr)
        return 1
    if addr + len(data) > 0x10000:
        print(f"{args.input}: {len(data)} bytes at 0x{addr:04X} runs past the "
              f"64K address space", file=sys.stderr)
        return 1

    upper = args.name.upper()
    out = [
        f"// Generated by tools/bin2c.py from {args.input} - do not edit.",
        "",
        f"#ifndef {upper}_H",
        f"#define {upper}_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define {upper}_ADDR 0x{addr:04X}u",
        "",
        f"static const uint8_t {args.name}[{len(data)}] = {{",
    ]
    for off in range(0, len(data), 12):
        row = ", ".join(f"0x{b:02X}" for b in data[off:off + 12])
        out.append(f"    {row},")
    out += ["};", "", f"#endif  // {upper}_H", ""]

    with open(args.output, "w") as f:
        f.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
